training_cfg:
  temperature: 0.26
  batch_size: 128
  lr: 0.00001
  lr_private: 0.00001
  epoch: 10
  epoch_private: 10
  weight_decay: 0.000001
  momentum: 0.9
  max_grad_norm: 1.0
  warmup_steps: 2000
  seed: 1024
  optimizer: "adam"

  bit: 64
  rounds: 100
  num_users: 10

  save_path: ""

model_cfg:
  model_path: ""
  alpha: ""
  beta: ""
  gamma: ""

data_cfg:
  dataset_name: "flickr"
  dataset_path: ""
  num_classes: 10
  noniid: true
  feature_iid: false
  label_iid: false
